### ISSUE TITLE
Add table of content in readme.md.

### ISSUE THREAD

**Issue by aditya-8-88** [aditya-8-88/Django-REST-API-Project#1]

**Comment by Abhishek022001** [comment]
Can i work on this issue?

**Comment by aditya-8-88** [comment]
Sure, feel free to take up the issue! Let me know if you have any questions or need assistance while working on it.

**Comment by AbdulmalikRaji** [comment]
Hello, is this issue still open for me to work on?

**Comment by aditya-8-88** [comment]
ya sure.
